seed: 0
input_channels: 7
num_actions: 901
n_rows: 15
n_cols: 15

memory_capacity: 500000
wait_buffer_size: 10000
target_update_freq: 1000

num_steps: 100000
learning_rate: 0.01
batch_size: 512

gamma: 0.99

use_wandb: True
wandb_project: "generals-ai"
wandb_run_name: "15x15_lr2e-5_step1e6_bs512_tgt1e3"