# Default configuration for training DQN on a single node with multiple GPUs

seed: 0
input_channels: 7
num_actions: 901
n_rows: 15
n_cols: 15

memory_capacity: 1000000
wait_buffer_size: 10000
target_update_freq: 1000

num_steps: 1000
learning_rate: 0.00002
batch_size: 512

gamma: 0.99

use_wandb: False