DIRECTIONS = [(1, 0), (-1, 0), (0, 1), (0, -1)]

TILE_EMPTY = -1
TILE_MOUNTAIN = -2
TILE_FOG = -3
TILE_OBSTACLE = -4

# Opponent Type Definitions
OPP_EMPTY = 0
OPP_ARMY = 1
OPP_CITY = 2
OPP_GENERAL = 3

MAX_NUM_TEAMS = 8